# Predicting how many goods were purchased by people through Social networking ads using Naive Bayes algorithm.

### Done by Abdul Farhan

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

In [3]:
dataset=pd.read_csv('/home/farhan/Downloads/archive (1)/Social_Network_Ads.csv')

In [4]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
X=dataset.iloc[:,[1,2,3]]

In [7]:
X

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

Now we will make an array becaue I just want the values.

In [8]:
X=dataset.iloc[:,[1,2,3]].values  #values function converts the data into array.

In [9]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [10]:
y=dataset.iloc[:,-1]

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
y=dataset.iloc[:,-1].values

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le=LabelEncoder()

In [16]:
X[:,0]=le.fit_transform(X[:,0])
# [:,0] means we are applying transformation to all rows of zero index.
#That means the male/female column will be converted to integers.

In [17]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

# Dividing the data for training and testing

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
len(X_train)

320

In [21]:
len(X_test)

80

In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
model=GaussianNB()

# Training the model

In [24]:
model.fit(X_train,y_train)

GaussianNB()

# Testing the trained model

In [25]:
model.predict(X_test)
# purchased 1           not purchased 0

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
X_test
# 1=male          0=Female

array([[0, 47, 47000],
       [1, 48, 33000],
       [0, 38, 65000],
       [0, 27, 17000],
       [1, 35, 108000],
       [0, 50, 20000],
       [1, 38, 59000],
       [0, 22, 55000],
       [0, 48, 138000],
       [0, 35, 77000],
       [1, 36, 60000],
       [1, 33, 43000],
       [1, 30, 49000],
       [1, 35, 61000],
       [1, 29, 43000],
       [0, 35, 60000],
       [0, 29, 47000],
       [1, 46, 59000],
       [1, 20, 86000],
       [0, 28, 44000],
       [0, 55, 130000],
       [0, 28, 85000],
       [0, 29, 83000],
       [0, 39, 75000],
       [0, 22, 27000],
       [0, 47, 50000],
       [1, 35, 22000],
       [0, 28, 55000],
       [0, 48, 35000],
       [0, 40, 142000],
       [1, 24, 84000],
       [1, 29, 80000],
       [0, 41, 72000],
       [0, 36, 126000],
       [1, 48, 74000],
       [1, 41, 59000],
       [1, 32, 18000],
       [0, 37, 93000],
       [0, 58, 101000],
       [1, 37, 77000],
       [0, 27, 54000],
       [1, 38, 71000],
       [0, 33, 113000],
    

# Checking the accuracy of trained model

In [27]:
model.score(X_test,y_test)

0.925